### ISSUE TITLE
Mic, could you add an "auto paste" option in the settings? to allow addon automatically paste into the email body?

### ISSUE THREAD

**Issue by michsanto** [micz/ThunderAI#132]
Mic, could you add an "auto paste" option in the settings? to allow addon automatically paste into the email body?

**Comment by micz** [comment]
The addon can paste the text in the mail.
Choose a prompt with "reply" o "rewrite", then click on the answer once. It should select the answer, then click on the blu button.

**Comment by michsanto** [comment]
Micz,  
Thank you for your response. While I'm familiar with the process, it would be helpful to have a settings option that automates this when I click "rewrite" This would allow the revised text to appear directly in my email body without the need for selection or extra clicks, streamlining the process while still enabling me to review before sending.  

What are your thoughts?  

* I would also like this feature available in "Manage Prompts" to apply it to specific prompts for testing.

**Comment by micz** [comment]
Until version 2.0.1, the selection and importation into the mail window were automatic with the press of a button. However, the ChatGPT web interface has been changing too frequently, breaking this mechanism.
Now, two clicks are needed instead of one: one on the response text and another on the button.

I'm sorry there is no other way.

**Comment by michsanto** [comment]
Ok thank you 
good to try :)
Have a great day!
