### ISSUE TITLE
Improved Reply Prompt: Managing the last reply and the full thread differently.

### ISSUE THREAD

**Issue by Slotts86** [micz/ThunderAI#150]
We really love this tool!

We would have liked the tool to have taken into account which part of a long email thread that chat gpt should respond to (the latest reply) and which part of the email thread (previously already answered) that it may have as a background to previous emails. 
It would be good if the delimitation or prompt was sent with over to chat gpt which paragraph is the latest and which is previously already answered mail. As it is now, the entire email thread is sent over in one piece, which means that chat gpt answers already answered questions, sums up previous things, etc.

Then we wonder if there is a manual (So you as a technical idiot can connect it yourself and make the database) on how to connect the device to a database or a web page from which chat gpt can retrieve information and answers to questions in the email. 

Best regards Axel

**Comment by micz** [comment]
I think it could possible, after implementing #146, to do something like this:

`Reply to the following email [selected_text], considering that is the full thread of emails [full_body]`.

Where `[selected text]` is the last email that the user has to manually select and `[full_body]` is the full message body.
It should be verified how ChatGPT interprets a prompt like this, but I think it could be worth trying.

Regarding your last question, I’ve never tried something like that. It really depends on the tool you’re using, but I think you could find a tutorial or an AI expert forum online to ask that question.

**Comment by micz** [comment]
In pre-release version [2.3.0pre2](https://github.com/micz/ThunderAI/releases/tag/v2.3.0pre2) you'll find the necessary features to test your prompt.
Please refer to the release notes for more information.

You can use a prompt like this:

`Reply to the following email "{%selected_text%}", considering that the full thread of emails is the following "{%mail_html_body%}". Do not add the subject line to the response.`

To use this, you need to select the text of the initial email. ThunderAI will then also send the full HTML body. Alternatively, using the placeholder `{%mail_text_body%}`, you can send the text version instead.

Testing this prompt was challenging because I often reached the maximum limit of 30,000 characters.
I've added an option to adjust the limit, as it may vary depending on the AI you’re using. The limit is fixed only for the ChatGPT Web Interface.

**Comment by micz** [comment]
Released in version 2.3.0.
