### ISSUE TITLE
Responses with formatting lose formatting when selected

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#70]
Should ChatGPT generate a response with a list, the list formatting is not preserved when brought into TB. Instead, the full list is put into a paragraph without any bullets or numeration.

**Comment by micz** [comment]
I managed to replicate the bug.
I'm sorry, it won't be fast because I need to rewrite the methods from scratch to also consider the formatting when importing in the response.

**Comment by micz** [comment]
Please, find here a pre-release version: [thunderai-v1.1.4pre1.zip](https://github.com/user-attachments/files/15905383/thunderai-v1.1.4pre1.zip)

May you use it for a few days to test it?
In my tests it keeps the formatting.

Before importing it in Thunderbird, remember to rename the file from `thunderai-v1.1.4pre1.zip` to `thunderai-v1.1.4pre1.xpi` (different extension).

If you have to return to the last published version **do not remove** the extension, but install the last one over this one.
Otherwise you'll lose the settings and the custom prompts.

Thank you.

**Comment by micz** [comment]
I found a bug that changes the order of some parts of the text under certain conditions.
Please wait for the next pre-release, which I am going to publish soon.

**Comment by micz** [comment]
Version 1.1.4pre2 should be ok.
You can get it from here: https://github.com/micz/ThunderAI/releases/tag/v1.1.4pre2

**Comment by micz** [comment]
This should be the last pre-release before the final 1.1.4 release.
I added an option to activate the "keep the format" feature. This option is off by default, so you have to turn it on to use it.
I did it this way to preserve the previous behavior, which is the one everyone is accustomed to.


The prelease is available here: https://github.com/micz/ThunderAI/releases/tag/v1.1.4pre3

**Comment by micz** [comment]
Fixed in version 1.1.4.
